# Generated by Django 2.2.6 on 2019-11-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0002_auto_20191125_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makale',
            old_name='içerik',
            new_name='icerik',
        ),
    ]
