# Generated by Django 2.2.6 on 2019-11-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0003_auto_20191125_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Foto Ekle'),
        ),
    ]
