# Generated by Django 2.2.6 on 2019-12-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.AlterModelOptions(
            name='makale',
            options={'ordering': ['-oluşturmaZamanı']},
        ),
    ]
