# Generated by Django 2.2.6 on 2020-01-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0006_auto_20191215_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makale',
            options={'ordering': ['-olusturmaZamani']},
        ),
        migrations.RenameField(
            model_name='makale',
            old_name='oluşturmaZamanı',
            new_name='olusturmaZamani',
        ),
    ]
